GenererLeCrudBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: GenererLeCrudBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        departure:
            type: string
            length: '4'
        arrival:
            type: string
            length: '4'
        pilot:
            type: string
            length: 255
        freeSeats:
            type: integer
        takeofTime:
            type: datetime

    manyToOne:
        planeModel:
            targetEntity: PlaneModel
            joinColumn:
                name: plane_model_id
                referencedColumnName: id
        terrainDeparture:
            targetEntity: Terrain
            inversedBy: departingFlights
            joinColumn:
                name: terrain_departure_id
                referencedColumnName: id
        terrainArrival:
            targetEntity: Terrain
            inversedBy: arrivingFlights
            joinColumn:
                name: terrain_arrival_id
                referencedColumnName: id

    oneToMany:
        reservations:
            targetEntity: Reservation
            mappedBy: flight
    lifecycleCallbacks: {  }
