GenererLeCrudBundle\Entity\Reservation:
    type: entity
    table: null
    repositoryClass: GenererLeCrudBundle\Repository\ReservationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        nbSeats:
            type: integer

    manyToOne:
        flight:
            targetEntity: Flight
            inversedBy: reservations
            joinColumn:
                name: flight_id
                referencedColumnName: id

    manyToMany:
        users:
            targetEntity: User
            joinTable:
                name: reservations_users
                joinColumns:
                  reservation_id:
                    referencedColumnName: id
                inverseJoinColumns:
                  user_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
